### ISSUE TITLE
Marking false positives with an inline "pragma: allowlist secret" not working

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#118]
Steps to repro:

- User runs secureli scan, secret detected by detect-secrets
- // pragma: allowlist secret added to line of code with false positive
- User runs secureli scan again, secret still detected

**Comment by hartonor-slalom** [comment]
looks like it is a user error.
Apparently the ignore comment is failing because the code is too long, and linter reformat the code such that it's no longer inline. that's why the ignore comment does not work. Will revisit this issue if it happen again
