### ISSUE TITLE
On `secureli init`, install latest released version of hooks

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#159]
**User Story**
As a developer, when I initialize a git repo using `secureli`, the version of the hooks installed should be the latest released version, so I can start my development effort using the latest and greatest hooks. 

**Acceptance Criteria**
- When running `secureli init` **for the first time** on a repo or running `secureli init --reset`
  - The latest released version for each hook should be installed (i.e. latest released version of detect-secrets, black, etc)
  - The behavior is the same as what happens when the user runs `secureli update --latest`
- When running `secureli init` on a repo that has already has a .pre-commit-config.yaml configuration file
  - No changes are made to hooks

**Technical Notes**
- Current behavior is that `secureli init` installs hooks with specific versions associated with each hook (static config in our own repo)
- `secureli update --latest` just calls pre-commit to update the hooks configured

**Comment by calebtonn** [comment]
Let's refine this story further

**Comment by kevin-orlando** [comment]
Closing. This was resolved from https://github.com/slalombuild/secureli/pull/322
