### ISSUE TITLE
Enable semantic versioning through GitHub app

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#185]
Current pipeline uses personal access token to enable semantic versioning. Since GitHub doesn't have the option of using a service/admin account, the most feasible option that allows us to get away from using a personal access token is using a GitHub app.

**Acceptance Criteria**
- Pipeline is able to successfully continue to perform semantic versioning of our application, without the use of a personal access token

**Comment by chrisba11** [comment]
Here is my PR for this: https://github.com/slalombuild/secureli/pull/195

I used the wrong ticket number in my branch name, so I wanted to link it here so there's a trail to follow.

**Comment by chrisba11** [comment]
This has been completed in PR #272. Leaving open because I am using the same ticket number to handle switching all uses of Sascha's PAT to using the `actions-helper` GH App token.
