### ISSUE TITLE
Latest version of semver introduces breaking change

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#232]

**Comment by sbates** [comment]
I think the first thing to do is to strip all the versioning, packaging and publishing out of the pipeline and then re-add it all one by one, starting with semver. I'm going use this ticket as a baseline to remove everything. Then ideally the order of adding things back is: 

- semver is pushing a version back to main
- a github release is created with the new version
- the release is noticed and pushed to homebrew
- the release is noticed and pushed to pypi - pypi actually did notice a new version and pushed it without needing a github release created. I don't know how we feel about this.
