### ISSUE TITLE
Add API URL for observability backend to `.secureli.yaml` file

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#248]
Currently, we use environment variables to configure a New Relic API endpoint & API key for the purpose of uploading logs/telemetry.

The New Relic API Key is sensitive and should not be source controlled, but the API endpoint is not sensitive and would ideally be configured once and shared with the rest of the team. We should update our code to read the API endpoint (URL) from the `.secureli.yaml` file.

We also want to recognize/respect existing configurations that are using the `API_ENDPOINT` environment variable, so we should allow the environment variable to continue to be recognized and to override a configured value in the `.secureli.yaml` file.

The best way to read from an environment variable with the fallback option of reading from the `.secureli.yaml` config is probably to use [pydantic settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/).

A suggested key name in the `.secureli.yaml` is `api_endpoint`, and the default value (written on `secureli init` should be `https://log-api.newrelic.com/log/v1`)

Acceptance Criteria:
* If a user has API_ENDPOINT configured, we should read the URL from it
* If a user does not have the `API_ENDPOINT` environment variable configured, we should attempt to read the value from `.secureli.yaml`
* If a user has neither configured, we should not attempt to upload logs (this behavior is already implemented and should not be changed)
* On `secureli init`, we should set the value in `.secureli.yaml` to `https://log-api.newrelic.com/log/v1`

**Comment by kevin-orlando** [comment]
Open questions:

1. Should the user be prompted to add the new relic api_url to .secureli.yaml on `init`, should we expect users to add it to the file, or should it be added automatically?
    - One proposed option is to prompt the user during install to add it and default to the listed default value or an empty value if they choose not to add their api url.
2. Is there any need to verify that an API_KEY is present before uploading logs or should seCureLI attempt to post logs as long as there is a url?

**Comment by tdurk93** [comment]
@kevin-orlando yeah I think something like this is good. What do you think? We can wordsmith it together if this isn't best.
```
% secureli init
seCureLI has not yet been installed, install now? [Y/n]: y
Add lint pre-commit hook(s) for Python? [Y/n]: n
Configure endpoint for telemetry logs? [https://log-api.newrelic.com/log/v1]:
Set the API_KEY environment variable to enable telemetry.
```
