### ISSUE TITLE
Merge latest dependabot PRs

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#360]

**Comment by dlolaogundipe** [comment]
Repo has an automated bot when there's an update of dependencies. The bot will create new PRs but will not merge. Tyler and Caleb to review the PRs and merge. 
Tyler to re-visit the status of the platform and make decision whether to merge PRs on Jan 24th.

**Comment by tdurk93** [comment]
I merged these 9 dependabot PRs which got us all caught up, so we can close this ticket.
https://github.com/slalombuild/secureli/pull/327
https://github.com/slalombuild/secureli/pull/315
https://github.com/slalombuild/secureli/pull/338
https://github.com/slalombuild/secureli/pull/340
https://github.com/slalombuild/secureli/pull/341
https://github.com/slalombuild/secureli/pull/409
https://github.com/slalombuild/secureli/pull/352
https://github.com/slalombuild/secureli/pull/408
https://github.com/slalombuild/secureli/pull/406
