### ISSUE TITLE
Fix semantic-release configuration

### ISSUE THREAD

**Issue by tdurk93** [slalombuild/secureli#365]
Reviewing the documentation for [semantic-release](https://python-semantic-release.readthedocs.io/en/latest/configuration.html), our configuration seems to be incorrect for a number of options. This has resulted in PRs marked with `chore:` not being promoted as releases, even though the configuration would appear to indicate that they are.

**Comment by calebtonn** [comment]
Merged and published to home-brew but now a different error is popping up. Looking into that now
