### ISSUE TITLE
Exclude binary files from secrets scans

### ISSUE THREAD

**Issue by tdurk93** [slalombuild/secureli#374]
Binary (non-text) files aren't able to scanned properly, and that causes them to print exceptions to the terminal during a scan. It looks like this:
```
[seCureLI] [WARN] - An unknown error occurred loading the file from <file path>
```

Here are a couple examples of binary files that throw an exception when we attempt to read them with a utf-8 encoding (after I started logging the underlying exception):
```
tests/data/backends/test_backend-0.1-py2.py3-none-any.whl: 'utf-8' codec can't decode byte 0xd8 in position 17: invalid continuation byte
```

```
tests/data/packages3/dinner/Dinner-1.0.tar.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

We should detect and exclude files that aren't utf-8.

**Comment by dlolaogundipe** [comment]
Core epic
