### ISSUE TITLE
Support Scanning a Subset of Source with seCureLI

### ISSUE THREAD

**Issue by tdurk93** [slalombuild/secureli#390]
We should expose the `--files` option in `pre-commit run` for users of seCureLI (specifically when using `secureli scan`). This would allow for e.g. testing linters for a single file (or set of files). Then we could test language detection & linters against test files within our repo, instead of having to clone additional repositories to test against each language.

Note: 
We will also want to update the files considered for language guessing. This should be a good starting point: https://github.com/slalombuild/secureli/blob/main/secureli/services/language_analyzer.py#L51

## Acceptance Criteria
* `--files` option is added to `secureli` and its value is passed on to `pre-commit`
* We restrict the files considered by the `LexerGuesser` to not include all files
* Appropriate automated tests are added
* README.md is updated

**Comment by dlolaogundipe** [comment]
core epic
