### ISSUE TITLE
Build Test against sample repos: Terraform

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#43]
### Description

As a dev on the seCureLI team, I want the build pipeline to check the tool against known ‘bad state’ repos, to ensure that the tool is not only passing unit tests and ‘not failing others’, but also that it is actively catching security issues, to ensure that the project is doing what it was designed to do.

### Technical Details

* Will require finding, or creating git repos that the pipeline can access that have secrets embedded in them.
* create repo as part of the Secure Build project
* Language Supported: Terraform
* Should only cover detect-secrets errors

### Acceptance Criteria

* Repo identified or created with the supporting language with 1+ secrets saved to it (fake secrets, of course)
* When the tool runs and successfully throws and error (expected behavior) the build does not fail.
* If the tool runs and does NOT throw an error (unexpected behavior) the build fails, as the tool did not properly detect the error.

**Comment by blonienc** [comment]
Closing out as this will be addressed in https://github.com/slalombuild/secureli/issues/129.
