### ISSUE TITLE
Rename integration-test folder to smoke-test (only if history can be preserved)

### ISSUE THREAD

**Issue by JordoHeffernan** [slalombuild/secureli#437]
_As a secureli maintainer I don't love that our smoke tests are called integrations tests_

## AC

1. Change the folder name `integration tests` to `smoke tests`
2. Only do this if we can preserve in some way our existing GitHub integration tests history (lives in [Actions](https://github.com/slalombuild/secureli/actions/workflows/integration_testing.yml))

**Comment by rt-slalom** [comment]
Here's some Post merge test evidence:
New Smoke Testing Workflow created, stage renamed in Publish workflow, and historical integration testing maintained in older publishing runs.

![Image](https://github.com/slalombuild/secureli/assets/85907688/46708486-3cc3-4f39-9b96-2fd6f1010da4)
![Image](https://github.com/slalombuild/secureli/assets/85907688/66e3d4d4-8f43-45de-9c75-5c91bf3cdac5)
