### ISSUE TITLE
Create command for users to submit custom regex pattern for security scan

### ISSUE THREAD

**Issue by JordoHeffernan** [slalombuild/secureli#460]
_As a user, I want to be able to have SeCureLi scan for custom patterns specific for my security concerns_

## AC
1. Add a new item to `.secureli.yaml` called `custom_scan_patterns` that is an empty list
2. ~~Create a new command called `add_custom_scan_pattern` (name suggestions?)~~ Expand Update command to include pattern additions
3. Command accepts a flag --new_pattern which can be added multiple times, each flag accepts a string
4. User input is checked and must be a regex pattern. if it pass the check, it is saved in config as an item in custom_scan_patterns
  a. If it fails, present error message to user 
5.  When the pre-commit scan runs, in addition to default security checks, and the items check by work completed in #435 also check for all patterns in custom_scan_patterns
6. Add documentation - Readme

### Notes
- Rather than creating this as a new command, we could make it a prompt as a part of init and/or update

**Comment by rt-slalom** [comment]
Completed development and unit tests for steps 1-4, work in linked branch `feature/secureli-460-custom-regex`. Steps 5-6 must still be completed.
