### ISSUE TITLE
Add ability to exclude files from the PII Scan

### ISSUE THREAD

**Issue by JordoHeffernan** [slalombuild/secureli#486]
_As a user, I want to be able set the PII scan to ignore specific files in my repo_

## AC

1. Add flag `--pii-exclude-file` to `scan` command
  a. can be added multiple times
  b. flag takes file path as a string and passes it to pii-scan service to ignore
2. Add `pii-exclude-file` config to .secureli.yaml 
  a. pii-scan respects this config
4. Update relevant documentation in README.md to reflect these changes

**Comment by blonienc** [comment]
Completed by @tristanl-slalom in this ticket: https://github.com/slalombuild/secureli/issues/558.
