### ISSUE TITLE
Discarding Invalid Results

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#55]
Over the course of a run, changes made to the filesystem outside of seCureLI may render linter results outdated or otherwise incorrect. For example, switching branches or merging from one's main branch might invalidate analysis in progress. seCureLI should recognize these conditions, such as modified, missing, or read-only files requiring modification, and simply discard them from the results. The summary should include a notice of these discards along with their reason, and the client will exit with a non-zero status code to indicate the incomplete result.

**Comment by JordoHeffernan** [comment]
Closing due to overmangement of integrations causing potential extensibility issues
