### ISSUE TITLE
Prompt user to move to version of secureli referenced in yaml file

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#58]
A developer may have a pre-existing version of secureli installed, and then clone a repo that has a reference to a different version of secureli configured for the repo. In this case, when running secureli, the application should prompt the developer to upgrade/downgrade to the version of secureli referenced in the .secureli.yaml file.

**Acceptance Criteria**
- the version of securli is saved/referenced in the .secureli.yaml file
- If a user runs secureli against a repo, and the version of the application matches the version of secureli configured for the repo, the operation continues normally
- If a user runs secureli against a repo, and the version of the application does not match the version of secureli configured for the repo, the user if prompted if they would like to upgrade/downgrade to the version configured for the repo
  - If the user agrees to upgrade/downgrade, TBD
  - If the user does not want to upgrade/downgrade, TBD

**Comment by a-e-benson** [comment]
I don't have the necessary privileges to assign this story to myself. I'm staking my claim here.

**Comment by a-e-benson** [comment]
Q: Since this a new feature, what should happen to repos that do not have the version set in .secureli.yaml?

**Comment by gabenegron** [comment]
Based on 1/10/2024 refinement, this is being deprioritized. What we are focusing on is the version of pre-commit and the hooks installed are pinned to the desired version.
