### ISSUE TITLE
secureli init fails with No such file or directory: 'pre-commit' error

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#80]
hartonor@C02GKP9MMD6M my-reactapp % secureli init
SeCureLI has not been setup yet.
Initialize SeCureLI now? [Y/n]: Y
Detected the following languages:
- TypeScript: 100%
Overall Detected Language: TypeScript
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/secureli/main.py │
│ :55 in init                                                                                      │
│                                                                                                  │
│    52 │   """                                                                                    │
│    53 │   Detect languages and initialize pre-commit hooks and linters for the project           │
│    54 │   """                                                                                    │
│ ❱  55 │   container.initializer_action().initialize_repo(Path("."), reset, yes)                  │
│    56                                                                                            │
│    57                                                                                            │
│    58 @app.command()                                                                             │
│                                                                                                  │
│ ╭─── locals ────╮                                                                                │
│ │ reset = False │                                                                                │
│ │   yes = False │                                                                                │
│ ╰───────────────╯                                                                                │
│                                                                                                  │
│ /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/secureli/actions │
│ /initializer.py:26 in initialize_repo            
... // there are some more stuffs here
... // there are some more stuffs here
... // there are some more stuffs here

FileNotFoundError: [Errno 2] No such file or directory: 'pre-commit'

**Comment by centenor** [comment]
Working on this issue.

The resolution I will be putting in place is as follows - 

* Move pre-commit to being a required dependency. This should force the pip installation to pull that package down
* Updating the homebrew formula creation script to filter out packages that are needed for pip but not the homebrew formula
* Updating lock file to reflect pre-commit being moved to a dependency
